@php
    $types = ['building' => 'Gedung', 'library' => 'Perpustakaan', 'worship_place' => 'Tempat ibadah', 'green_space' => 'Ruang hijau', 'parking' => 'Parkir', 'pedestrian_area' => 'Area pedestrian', 'shuttle_stop' => 'Halte shuttle'];
    $statuses = ['accessible' => 'Aksesibel', 'partially_accessible' => 'Sebagian aksesibel', 'inaccessible' => 'Tidak aksesibel', 'not_assessed' => 'Belum dinilai'];
@endphp
@csrf
@isset($location) @method('put') @endisset
<div class="field"><label for="name">Nama lokasi</label><input id="name" name="name" value="{{ old('name', $location->name ?? '') }}" required @error('name') aria-describedby="name-error" aria-invalid="true" @enderror>@error('name')<p class="field-error" id="name-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="location_type">Tipe lokasi</label><select id="location_type" name="location_type" required @error('location_type') aria-describedby="location_type-error" aria-invalid="true" @enderror>@foreach($types as $value => $label)<option value="{{ $value }}" @selected(old('location_type', $location->location_type ?? '') === $value)>{{ $label }}</option>@endforeach</select>@error('location_type')<p class="field-error" id="location_type-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="description">Deskripsi</label><textarea id="description" name="description" rows="3" @if($errors->has('description')) aria-describedby="description-error" aria-invalid="true" @endif>{{ old('description', $location->description ?? '') }}</textarea>@error('description')<p class="field-error" id="description-error">{{ $message }}</p>@enderror</div>
<div class="field-grid">
    <div class="field"><label for="latitude">Latitude</label><input id="latitude" name="latitude" type="number" step="0.0000001" min="-90" max="90" value="{{ old('latitude', $location->latitude ?? '') }}" required @error('latitude') aria-describedby="latitude-error" aria-invalid="true" @enderror>@error('latitude')<p class="field-error" id="latitude-error">{{ $message }}</p>@enderror</div>
    <div class="field"><label for="longitude">Longitude</label><input id="longitude" name="longitude" type="number" step="0.0000001" min="-180" max="180" value="{{ old('longitude', $location->longitude ?? '') }}" required @error('longitude') aria-describedby="longitude-error" aria-invalid="true" @enderror>@error('longitude')<p class="field-error" id="longitude-error">{{ $message }}</p>@enderror</div>
</div>
<div class="field"><label for="accessibility_status">Status aksesibilitas</label><select id="accessibility_status" name="accessibility_status" required @error('accessibility_status') aria-describedby="accessibility_status-error" aria-invalid="true" @enderror>@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('accessibility_status', $location->accessibility_status ?? 'not_assessed') === $value)>{{ $label }}</option>@endforeach</select>@error('accessibility_status')<p class="field-error" id="accessibility_status-error">{{ $message }}</p>@enderror</div>
@error('area')<p class="field-error">{{ $message }}</p>@enderror
@isset($location)<div class="field"><label for="is_active">Status data</label><select id="is_active" name="is_active" required @error('is_active') aria-describedby="is_active-error" aria-invalid="true" @enderror><option value="1" @selected((string)old('is_active', (int)$location->is_active)==='1')>Aktif</option><option value="0" @selected((string)old('is_active', (int)$location->is_active)==='0')>Nonaktif</option></select>@error('is_active')<p class="field-error" id="is_active-error">{{ $message }}</p>@enderror</div>@endisset
<div class="actions"><button class="button button-primary" type="submit">Simpan lokasi</button><a class="button button-secondary" href="{{ route('admin.campuses.areas.locations.index', [$campus, $area]) }}">Batal</a></div>
