@php
    $availabilityOptions = ['available' => 'Tersedia', 'unavailable' => 'Tidak tersedia'];
    $conditionOptions = ['good' => 'Baik', 'needs_repair' => 'Perlu perbaikan', 'blocked' => 'Terhalang', 'broken' => 'Rusak'];
@endphp
@csrf @isset($locationFeature) @method('put') @endisset
@isset($features)<div class="field"><label for="accessibility_feature_id">Fasilitas</label><select id="accessibility_feature_id" name="accessibility_feature_id" required><option value="">Pilih fasilitas</option>@foreach($features as $feature)<option value="{{ $feature->id }}" @selected((string)old('accessibility_feature_id')===(string)$feature->id)>{{ $feature->name }}</option>@endforeach</select>@error('accessibility_feature_id')<p class="field-error">{{ $message }}</p>@enderror</div>@endisset
@isset($locationFeature)<div class="field"><label>Fasilitas</label><input value="{{ $locationFeature->accessibilityFeature->name }}" readonly></div>@endisset
<div class="field"><label for="availability_status">Ketersediaan</label><select id="availability_status" name="availability_status" required>@foreach($availabilityOptions as $value=>$label)<option value="{{ $value }}" @selected(old('availability_status',$locationFeature->availability_status??'available')===$value)>{{ $label }}</option>@endforeach</select>@error('availability_status')<p class="field-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="condition">Kondisi</label><select id="condition" name="condition" required>@foreach($conditionOptions as $value=>$label)<option value="{{ $value }}" @selected(old('condition',$locationFeature->condition??'good')===$value)>{{ $label }}</option>@endforeach</select>@error('condition')<p class="field-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="notes">Catatan</label><textarea id="notes" name="notes" rows="3">{{ old('notes',$locationFeature->notes??'') }}</textarea>@error('notes')<p class="field-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="last_checked_at">Waktu pemeriksaan</label><input id="last_checked_at" name="last_checked_at" type="datetime-local" value="{{ old('last_checked_at',isset($locationFeature) && $locationFeature->last_checked_at ? $locationFeature->last_checked_at->format('Y-m-d\TH:i') : '') }}">@error('last_checked_at')<p class="field-error">{{ $message }}</p>@enderror</div>
<div class="actions"><button class="button button-primary" type="submit">Simpan fasilitas lokasi</button><a class="button button-secondary" href="{{ route('admin.locations.features.index',$location) }}">Batal</a></div>
